POST http://localhost:3030/books/create 
Content-Type: application/json


{
    "author":"De Amicis",
    "title":"Libro Cuore",
    "price": 15.50,
    "isFeatured": true,
    "description": "Un libro sempre attuale"
}

####
GET http://localhost:3030/books