POST http://localhost:3030/books/create 
Content-Type: application/json

{
    "author":"Giovanni Muchacha",
    "title":"Art Attack",
    "price": 12.00,
    "isFeatured": false,
    "description": "Un libro per i tuoi attacchi d'arte"
}


####
GET http://localhost:3030/books