POST http://localhost:3030/books/create 
Content-Type: application/json

{
    "author":"Giovanni Merlino",
    "title":"Art",
    "price": 14.00,
    "isFeatured": false,
    "description": "Un libro"
}


####
GET http://localhost:3030/books