GET http://localhost:3030/getAuthors


####
POST http://localhost:3030/createAuthor
Content-Type: application/json

{
    "firstName": "Francesca",
    "lastName": "Pavone",
    "email": "ciccia.pa@gmail.com",
    "birthday": "35",
    "avatar":"picwow10.png"
}

####
GET http://localhost:3030/getAuthors/65f217789f363386c4e59f35

####
PATCH http://localhost:3030/updateAuthor/65f217789f363386c4e59f35
Content-Type: application/json

{
    "lastName":"Basile"
}
####

DELETE http://localhost:3030/deleteAuthor/65f217789f363386c4e59f35

####
GET http://localhost:3030/getAuthor/byName/mir

####
GET http://localhost:3030/getAuthor/byAge/39

####
GET http://localhost:3030/getUsers