

GET http://localhost:3030/getUsers




####


POST http://localhost:3030/createUser
Content-Type: application/json

{
    "firstName": "Vincenzo",
    "lastName": "Vaccaro",
    "email": "enzo.vaccaro@gmail.com",
    "password": "Enzo1234",
    "age": 62

}
####
POST http://localhost:3030/login
Content-Type: application/json

{
    "email": "enzo.vaccaro@gmail.com",
    "password": "Enzo1234"
}

