

GET http://localhost:3030/getUsers




####


POST http://localhost:3030/createUser
Content-Type: application/json

{
    "firstName": "Mirko",
    "lastName": "Vaccaro",
    "email": "mirko.vaccaro@gmail.com",
    "password": "Mirko1234",
    "age": 26

}
####
POST http://localhost:3030/login
Content-Type: application/json

{
    "email": "mirko.vaccaro@gmail.com",
    "password": "Mirko1234"
}

