POST http://localhost:3030/books/create 
Content-Type: application/json


{
    "author":"Mirko",
    "title":"Un libro fantastico",
    "price": 12.50,
    "isFeatured": false,
    "description": "che libro merdaviglioso."
}

####
GET http://localhost:3030/books