

GET http://localhost:3030/getUsers




####


POST http://localhost:3030/createUser
Content-Type: application/json

{
    "firstName": "Giulia",
    "lastName": "Vaccaro",
    "email": "giulia.vaccaro@gmail.com",
    "password": "Giulia1234",
    "age": 28

}
####
POST http://localhost:3030/login
Content-Type: application/json

{
    "email": "giulia.vaccaro@gmail.com",
    "password": "Giulia1234"
}

